[package]
name = "raccoonLang"
version = "0.1.0"
edition = "2021"

[dependencies]
ustr = "1.1.0"
tempdir = "0.3.7"
paste = "1.0.15"
icu = {version = "1.5.0", features = ["compiled_data"]}

[dev-dependencies]
parameterized = "2.0.0"